<?php
require 'vendor/autoload.php';
$app = new \atk4\ui\App('Загрузка наших мозгов...');
$app->initLayout('Centered');
$button = $app->add('Button');
$button->set('Follower');
$button->icon = 'comment';
$button->link ('https://www.youtube.com');
$button = $app->add('Button');
$button->set('Registration');
$button->icon = 'youtube';
$button->link ('https://www.e-klase.lv');
$button = $app->add('Button');
$button->set('Android site');
$button->icon = 'android';
$button->link ('https://www.android.com');
$button = $app->add('Button');
$button->set('My chess site');
$button->icon = 'delicious';
$button->link ('http://deniskariga.wixsite.com/chess-lessons-free');
